// feature.rs — Feature trait and built-in feature implementations for ta-init (v0.16.5).
//
// Each Feature is a small, focused struct that writes a specific subset of
// project files. Features are composable — a template declares which features
// it needs, and the engine applies them in order.

use std::{collections::HashMap, path::PathBuf};

// ── TemplateContext ──────────────────────────────────────────────────────────

/// Context passed to every Feature::apply() call.
pub struct TemplateContext {
    /// Absolute path to the project root.
    pub project_root: PathBuf,
    /// The human-readable project name (directory name or user-supplied).
    pub project_name: String,
    /// User-supplied and computed template variables.
    pub vars: HashMap<String, String>,
}

impl TemplateContext {
    pub fn ta_dir(&self) -> PathBuf {
        self.project_root.join(".ta")
    }
}

// ── Feature trait ────────────────────────────────────────────────────────────

/// A composable unit of project initialization logic.
///
/// Each implementation writes specific files/directories to the project tree.
/// Features are applied in the order declared by the template manifest.
pub trait Feature: Send + Sync {
    fn name(&self) -> &str;
    fn apply(&self, ctx: &TemplateContext) -> anyhow::Result<()>;
}

// ── KotlinVerifyFeature ──────────────────────────────────────────────────────

/// Marker feature — signals that this template uses Kotlin/Gradle verify steps.
///
/// The verify commands are written by the scaffold (workflow.toml.tera) rather
/// than this feature itself. apply() is intentionally a no-op.
pub struct KotlinVerifyFeature;

impl Feature for KotlinVerifyFeature {
    fn name(&self) -> &str {
        "kotlin-verify"
    }

    fn apply(&self, _ctx: &TemplateContext) -> anyhow::Result<()> {
        // No-op: verify commands come from the scaffold file (workflow.toml.tera).
        Ok(())
    }
}

// ── BmadPlannerFeature ───────────────────────────────────────────────────────

/// Writes BMAD role agent configs, .ta/bmad.toml, .mcp.json, and onboarding-goal.md.
///
/// Mirrors the logic in init.rs: generate_bmad_toml, generate_bmad_agent_configs,
/// generate_mcp_json, and generate_onboarding_goal (PragmaKotlin variant).
pub struct BmadPlannerFeature;

impl Feature for BmadPlannerFeature {
    fn name(&self) -> &str {
        "bmad-planner"
    }

    fn apply(&self, ctx: &TemplateContext) -> anyhow::Result<()> {
        let ta_dir = ctx.ta_dir();
        std::fs::create_dir_all(&ta_dir)?;

        write_bmad_toml(&ta_dir)?;
        write_bmad_agent_configs(&ta_dir)?;
        write_mcp_json(&ctx.project_root)?;
        write_onboarding_goal(&ta_dir, &ctx.project_name)?;

        Ok(())
    }
}

fn write_bmad_toml(ta_dir: &std::path::Path) -> anyhow::Result<()> {
    let path = ta_dir.join("bmad.toml");
    if path.exists() {
        return Ok(());
    }

    let default_home = if cfg!(target_os = "windows") {
        "%USERPROFILE%\\.bmad"
    } else {
        "~/.bmad"
    };

    let content = format!(
        r#"# BMAD machine-local configuration
# Generated by `ta init --template unreal-cpp/unity-csharp`
#
# BMAD is installed machine-locally (not in the project tree).
# Override with the TA_BMAD_HOME environment variable.

# Path to your local BMAD clone.
# Install: git clone https://github.com/bmad-code-org/BMAD-METHOD {default}
bmad_home = "{default}"

# Agent persona directory within bmad_home.
agents_dir = "agents"
"#,
        default = default_home,
    );
    std::fs::write(&path, content)?;
    println!("  Created .ta/bmad.toml");
    Ok(())
}

fn write_bmad_agent_configs(ta_dir: &std::path::Path) -> anyhow::Result<()> {
    let agents_dir = ta_dir.join("agents");
    std::fs::create_dir_all(&agents_dir)?;

    let roles = [
        ("bmad-pm", "Product Manager", "pm"),
        ("bmad-architect", "Software Architect", "architect"),
        ("bmad-dev", "Developer", "dev"),
        ("bmad-qa", "QA Engineer", "qa"),
    ];

    for (id, role_name, persona) in &roles {
        let path = agents_dir.join(format!("{}.toml", id));
        if path.exists() {
            continue;
        }
        let content = format!(
            r#"# BMAD agent config: {role}
# Generated by `ta init`
#
# The persona prompt is loaded from ${{bmad_home}}/agents/{persona}.md at runtime.
# bmad_home is defined in .ta/bmad.toml (or TA_BMAD_HOME env var).

name = "{id}"
role = "{role}"
persona_file = "${{bmad_home}}/agents/{persona}.md"

# Claude Code is the underlying runtime.
command = "claude"
injects_context_file = true
injects_settings = true
"#,
            role = role_name,
            id = id,
            persona = persona,
        );
        std::fs::write(&path, content)?;
        println!("  Created .ta/agents/{}.toml", id);
    }

    Ok(())
}

fn write_mcp_json(project_root: &std::path::Path) -> anyhow::Result<()> {
    let path = project_root.join(".mcp.json");
    if path.exists() {
        return Ok(());
    }

    let content = r#"{
  "mcpServers": {
    "ta": {
      "command": "ta",
      "args": ["mcp", "serve"],
      "description": "Trusted Autonomy governance server — staging, draft review, audit trail, policy"
    },
    "claude-flow": {
      "command": "claude-flow",
      "args": ["mcp", "serve"],
      "description": "Claude Flow swarm coordination — parallel agent tasks across module boundaries. Install: npm install -g @ruvnet/claude-flow"
    }
  }
}
"#;
    std::fs::write(&path, content)?;
    println!("  Created .mcp.json");
    Ok(())
}

fn write_onboarding_goal(ta_dir: &std::path::Path, project_name: &str) -> anyhow::Result<()> {
    let path = ta_dir.join("onboarding-goal.md");
    if path.exists() {
        return Ok(());
    }

    // Pragma Engine / Kotlin variant.
    let engine = "Pragma Engine";
    let lang = "Kotlin";
    let source_ext = "*.kt / *.kts";

    let content = format!(
        r#"# Onboarding Goal: {project} Discovery
#
# Run with: ta run --objective-file .ta/onboarding-goal.md
#           (title is derived from the first heading above)
#
# Prerequisites (must be installed before running):
#   - claude   : Claude Code CLI  (claude.ai/code)
#   - claude-flow : npm install -g @ruvnet/claude-flow
#   - BMAD     : git clone https://github.com/bmad-code-org/BMAD-METHOD ~/.bmad
#                (or set TA_BMAD_HOME to your clone path)
#
# What this goal produces:
#   docs/architecture.md         — Module map and key systems
#   docs/bmad/prd.md             — Product Requirements Document
#   docs/bmad/stories/sprint-1/  — Sprint-1 user stories

## Goal

Survey the **{project}** {engine} {lang} project and produce structured onboarding artefacts
using BMAD planning roles, Claude Flow swarm coordination, and TA draft governance.

## Scope

1. **Discovery** (bmad-architect role)
   - Walk the source tree ({src_ext}) and identify major modules, subsystems, and dependencies
   - Document current architecture in `docs/architecture.md`
   - Note technical debt, missing tests, and build warnings

2. **PRD** (bmad-pm role)
   - Interview the codebase to infer current feature set and gaps
   - Produce `docs/bmad/prd.md` with Goals, Non-Goals, and Success Metrics

3. **Sprint-1 Stories** (bmad-dev + bmad-qa roles)
   - Decompose the PRD into actionable stories
   - Write to `docs/bmad/stories/sprint-1/`
   - Each story: title, acceptance criteria, implementation notes, test plan

## Constraints

- Do not modify game source files during this discovery goal
- Write only to `docs/` and `.ta/`
- Flag any files that require human review before modification (especially {engine} config files)

## Done when

- [ ] `docs/architecture.md` created and reviewed
- [ ] `docs/bmad/prd.md` created and reviewed
- [ ] At least 3 sprint-1 stories written to `docs/bmad/stories/sprint-1/`
"#,
        project = project_name,
        engine = engine,
        lang = lang,
        src_ext = source_ext,
    );
    std::fs::write(&path, content)?;
    println!("  Created .ta/onboarding-goal.md");
    Ok(())
}

// ── GitAdapterFeature ────────────────────────────────────────────────────────

/// Writes .gitattributes with project-memory merge strategy hint (if .git exists).
///
/// Mirrors generate_gitattributes_project_memory in init.rs.
pub struct GitAdapterFeature;

impl Feature for GitAdapterFeature {
    fn name(&self) -> &str {
        "git-adapter"
    }

    fn apply(&self, ctx: &TemplateContext) -> anyhow::Result<()> {
        if !ctx.project_root.join(".git").exists() {
            return Ok(());
        }
        write_gitattributes_project_memory(&ctx.project_root)
    }
}

fn write_gitattributes_project_memory(project_root: &std::path::Path) -> anyhow::Result<()> {
    let path = project_root.join(".gitattributes");
    let entry = ".ta/project-memory/*.json merge=union\n";

    if path.exists() {
        let content = std::fs::read_to_string(&path)?;
        if content.contains(".ta/project-memory/") {
            return Ok(()); // Already present.
        }
        let mut existing = content;
        if !existing.ends_with('\n') {
            existing.push('\n');
        }
        existing
            .push_str("# TA project-memory: use union merge to reduce conflicts (v0.15.13.3)\n");
        existing.push_str(entry);
        std::fs::write(&path, existing)?;
    } else {
        std::fs::write(
            &path,
            format!(
                "# .gitattributes — generated by `ta init`\n\
                 # TA project-memory: use union merge to reduce conflicts (v0.15.13.3)\n\
                 {}",
                entry
            ),
        )?;
    }
    println!("  Updated .gitattributes (project-memory merge strategy)");
    Ok(())
}

// ── PerforceAdapterFeature ───────────────────────────────────────────────────

/// No-op placeholder for Perforce VCS adapter support (future).
pub struct PerforceAdapterFeature;

impl Feature for PerforceAdapterFeature {
    fn name(&self) -> &str {
        "perforce-adapter"
    }

    fn apply(&self, _ctx: &TemplateContext) -> anyhow::Result<()> {
        // No-op: Perforce adapter support is planned for a future phase.
        Ok(())
    }
}

// ── PragmaContextFeature ─────────────────────────────────────────────────────

/// Writes Pragma-specific files: pragma-planner.toml, kotlin constitution,
/// seeds memory entries, and captures recent git commits.
///
/// Mirrors generate_pragma_planner_agent, generate_pragma_constitution,
/// seed_memory_entries (PragmaKotlin arm), and capture_git_context_for_pragma
/// from init.rs.
pub struct PragmaContextFeature;

impl Feature for PragmaContextFeature {
    fn name(&self) -> &str {
        "pragma-context"
    }

    fn apply(&self, ctx: &TemplateContext) -> anyhow::Result<()> {
        let ta_dir = ctx.ta_dir();
        std::fs::create_dir_all(&ta_dir)?;

        write_pragma_planner_agent(&ta_dir)?;
        write_pragma_constitution(&ta_dir)?;
        seed_pragma_memory_entries(&ta_dir, &ctx.project_root)?;

        if ctx.project_root.join(".git").exists() {
            capture_git_context_for_pragma(&ta_dir, &ctx.project_root);
        }

        Ok(())
    }
}

fn write_pragma_planner_agent(ta_dir: &std::path::Path) -> anyhow::Result<()> {
    let agents_dir = ta_dir.join("agents");
    std::fs::create_dir_all(&agents_dir)?;

    let path = agents_dir.join("pragma-planner.toml");
    if path.exists() {
        return Ok(());
    }

    let content = r#"# Pragma BMAD Planner Agent
# Generated by `ta init --template pragma`
#
# This agent is pre-loaded with Pragma Engine 2026.1.0 architecture context
# and BMAD milestone decomposition methodology.
#
# Run: ta run "Pragma architecture discovery" --agent pragma-planner
# Or:  ta plan pragma

name = "pragma-planner"
role = "Pragma BMAD Planner"
persona_file = "${bmad_home}/agents/architect.md"

# Claude Code is the underlying runtime.
command = "claude"
injects_context_file = true
injects_settings = true

# Architecture context injected into every session.
[context]
pragma_version = "2026.1.0"
docs_url = "https://pragma.gg/docs/2026.1.0"

# Pragma service catalog (2026.1.0).
[context.service_catalog]
player      = "Account management, identity, entitlements, and player data lifecycle"
matchmaking = "Lobby creation, ticket flow, matchmaking algorithms, and game instance launch"
commerce    = "Virtual currency, catalog items, purchase flow, and receipt validation"
social      = "Friends list, party system, chat, and presence"
game_data   = "Game config, flags, in-game item definitions, and live-ops data"
ops         = "Operator portal hooks, game operations tooling, and internal dashboards"
portal      = "Operator-facing web portal backend (REST APIs consumed by Pragma Portal UI)"

# Plugin extension points (implement interfaces in pragma-plugin-common).
[context.extension_points]
matchmaking_plugin    = "MatchmakingPlugin — override ticket scoring, capacity management"
commerce_plugin       = "CommercePlugin   — custom purchase validation, currency rules"
player_data_plugin    = "PlayerDataPlugin — custom player record fields and lifecycle hooks"
game_instance_plugin  = "GameInstancePlugin — launch params, server selection logic"

# BMAD methodology configuration.
[context.bmad]
method = "milestone-decomposition"
roles  = ["pm", "architect", "dev", "qa"]
phases = ["discovery", "prd", "sprint-stories"]

# Discovery step: scanned on `ta plan pragma` or first run.
[discovery]
scan_patterns = [
    "pragma-core/src/main/resources/**/*.yaml",
    "pragma-ext-service/src/**/*.kt",
    "pragma-plugin-common/src/**/*.kt",
    "**/settings.gradle.kts",
    "**/settings.gradle",
    "**/build.gradle.kts",
]
interview_topics = [
    "Which Pragma services are deployed (player/matchmaking/commerce/social/game-data/ops/portal)?",
    "Which services have custom plugins implemented?",
    "What SDK integrations are active (Unreal Engine / Unity / Web)?",
    "What is the current Pragma server version?",
    "What are the top 3 active development priorities?",
]
"#;
    std::fs::write(&path, content)?;
    println!("  Created .ta/agents/pragma-planner.toml");
    Ok(())
}

fn write_pragma_constitution(ta_dir: &std::path::Path) -> anyhow::Result<()> {
    let const_dir = ta_dir.join("constitutions");
    std::fs::create_dir_all(&const_dir)?;
    let path = const_dir.join("kotlin.yaml");
    if path.exists() {
        return Ok(());
    }

    let content = r#"# Kotlin / Pragma Engine Constitution
# Generated by `ta init --template pragma`
# Enforces Kotlin coding standards and Pragma plugin conventions.

name: kotlin
description: "Kotlin and Pragma Engine development constitution"

rules:
  - "All Kotlin code must pass `./gradlew ktlintCheck` before committing"
  - "Pragma plugin implementations must not call deprecated extension-point APIs"
  - "Never modify generated files in build/ or .gradle/ directories"
  - "Suspend functions must use structured concurrency — avoid GlobalScope"
  - "Pragma config files in pragma-core/src/main/resources/ require explicit review before modification"
  - "Do not introduce new external dependencies without justifying in the PR description"
  - "Pragma plugin interfaces from pragma-plugin-common must be implemented fully — no no-op stubs in production code"
  - "All new Kotlin files must have a package declaration matching the Gradle module structure"
"#;
    std::fs::write(&path, content)?;
    println!("  Created .ta/constitutions/kotlin.yaml");
    Ok(())
}

fn seed_pragma_memory_entries(
    ta_dir: &std::path::Path,
    _project_root: &std::path::Path,
) -> anyhow::Result<()> {
    let memory_dir = ta_dir.join("memory");
    std::fs::create_dir_all(&memory_dir)?;

    let seeds: Vec<(String, serde_json::Value)> = vec![
        (
            "arch:pragma-service-catalog".into(),
            serde_json::json!({
                "services": [
                    "player",
                    "matchmaking",
                    "commerce",
                    "social",
                    "game-data",
                    "ops",
                    "portal"
                ],
                "description": "Pragma 2026.1.0 core service modules",
                "source": "Pragma Engine 2026.1.0 architecture docs"
            }),
        ),
        (
            "conv:pragma-plugin-extension-model".into(),
            serde_json::json!({
                "convention": "Pragma plugins implement interfaces in pragma-plugin-common. Each service exposes ext points via abstract classes (e.g., MatchmakingPlugin, CommercePlugin). Override only the methods you need; super() calls must be preserved unless the Pragma docs say otherwise.",
                "source": "Pragma Engine plugin development guide"
            }),
        ),
        (
            "conv:pragma-kotlin-async".into(),
            serde_json::json!({
                "convention": "Pragma server code is single-threaded Kotlin coroutines (kotlinx.coroutines). Use suspend functions and structured concurrency. Avoid blocking calls on the main dispatcher — offload to Dispatchers.IO when doing filesystem or network I/O.",
                "source": "Pragma Engine Kotlin conventions"
            }),
        ),
    ];

    for (key, value) in &seeds {
        let filename = key.replace([':', '/'], "_");
        let path = memory_dir.join(format!("{}.json", filename));
        let entry = serde_json::json!({
            "key": key,
            "value": value,
            "tags": ["init-seed", "auto-detected"],
            "source": "ta-init",
            "created_at": chrono::Utc::now().to_rfc3339(),
        });
        std::fs::write(&path, serde_json::to_string_pretty(&entry)?)?;
    }

    if !seeds.is_empty() {
        println!("  Seeded {} memory entries", seeds.len());
    }

    Ok(())
}

fn capture_git_context_for_pragma(ta_dir: &std::path::Path, project_root: &std::path::Path) {
    let output = std::process::Command::new("git")
        .args(["log", "--oneline", "-20"])
        .current_dir(project_root)
        .output();

    match output {
        Ok(out) if out.status.success() => {
            let log = String::from_utf8_lossy(&out.stdout).to_string();
            let lines: Vec<&str> = log.lines().collect();
            let memory_dir = ta_dir.join("memory");
            let _ = std::fs::create_dir_all(&memory_dir);
            let entry = serde_json::json!({
                "key": "vcs:recent-commits",
                "value": {
                    "commits": lines,
                    "count": lines.len(),
                    "adapter": "git",
                },
                "tags": ["vcs", "git", "init-seed"],
                "source": "ta-init pragma",
                "created_at": chrono::Utc::now().to_rfc3339(),
            });
            let path = memory_dir.join("vcs_recent_commits.json");
            if let Ok(json) = serde_json::to_string_pretty(&entry) {
                if std::fs::write(&path, json).is_ok() {
                    println!(
                        "  Captured {} recent git commits for planner context",
                        lines.len()
                    );
                }
            }
        }
        _ => {
            println!("  Note: could not read git log — run `git init` if this is a new repo");
        }
    }
}

// ── Ue5ContextFeature ────────────────────────────────────────────────────────

/// Seeds Unreal Engine 5 memory conventions into .ta/memory/.
///
/// Mirrors the UnrealCpp arm of seed_memory_entries in init.rs.
pub struct Ue5ContextFeature;

impl Feature for Ue5ContextFeature {
    fn name(&self) -> &str {
        "ue5-context"
    }

    fn apply(&self, ctx: &TemplateContext) -> anyhow::Result<()> {
        let ta_dir = ctx.ta_dir();
        let memory_dir = ta_dir.join("memory");
        std::fs::create_dir_all(&memory_dir)?;

        let seeds: Vec<(String, serde_json::Value)> = vec![
            (
                "conv:ue5-object-ownership".into(),
                serde_json::json!({
                    "convention": "Use TObjectPtr<T> for UPROPERTY references (UE5+). Raw pointers for non-UPROPERTY temporaries only.",
                    "source": "UE5 coding conventions"
                }),
            ),
            (
                "conv:ue5-game-thread".into(),
                serde_json::json!({
                    "convention": "All UObject operations must occur on the game thread. Use AsyncTask(ENamedThreads::GameThread, ...) to marshal back from worker threads.",
                    "source": "UE5 threading rules"
                }),
            ),
            (
                "conv:ue5-uproperties".into(),
                serde_json::json!({
                    "convention": "Expose editable properties with UPROPERTY(EditAnywhere, BlueprintReadWrite, Category=...). Use UFUNCTION(BlueprintCallable) for Blueprint-accessible methods.",
                    "source": "UE5 reflection system"
                }),
            ),
        ];

        for (key, value) in &seeds {
            let filename = key.replace([':', '/'], "_");
            let path = memory_dir.join(format!("{}.json", filename));
            let entry = serde_json::json!({
                "key": key,
                "value": value,
                "tags": ["init-seed", "auto-detected"],
                "source": "ta-init",
                "created_at": chrono::Utc::now().to_rfc3339(),
            });
            std::fs::write(&path, serde_json::to_string_pretty(&entry)?)?;
        }

        if !seeds.is_empty() {
            println!("  Seeded {} UE5 memory entries", seeds.len());
        }

        Ok(())
    }
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn make_ctx(dir: &TempDir) -> TemplateContext {
        TemplateContext {
            project_root: dir.path().to_path_buf(),
            project_name: "TestProject".to_string(),
            vars: HashMap::new(),
        }
    }

    #[test]
    fn kotlin_verify_feature_noop() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(&dir);
        let feat = KotlinVerifyFeature;
        assert_eq!(feat.name(), "kotlin-verify");
        feat.apply(&ctx).unwrap(); // Must not create any files.
        assert!(!dir.path().join(".ta").exists());
    }

    #[test]
    fn bmad_planner_feature_creates_files() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(&dir);
        let feat = BmadPlannerFeature;
        assert_eq!(feat.name(), "bmad-planner");
        feat.apply(&ctx).unwrap();

        let ta_dir = dir.path().join(".ta");
        assert!(ta_dir.join("bmad.toml").exists());
        assert!(ta_dir.join("agents").join("bmad-pm.toml").exists());
        assert!(ta_dir.join("agents").join("bmad-architect.toml").exists());
        assert!(ta_dir.join("agents").join("bmad-dev.toml").exists());
        assert!(ta_dir.join("agents").join("bmad-qa.toml").exists());
        assert!(dir.path().join(".mcp.json").exists());
        assert!(ta_dir.join("onboarding-goal.md").exists());

        let goal = std::fs::read_to_string(ta_dir.join("onboarding-goal.md")).unwrap();
        assert!(goal.contains("TestProject"));
        assert!(goal.contains("Pragma Engine"));
        assert!(goal.contains("*.kt / *.kts"));
    }

    #[test]
    fn bmad_planner_idempotent() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(&dir);
        let feat = BmadPlannerFeature;
        feat.apply(&ctx).unwrap();
        feat.apply(&ctx).unwrap(); // Should not error on second call.
        let ta_dir = dir.path().join(".ta");
        assert!(ta_dir.join("bmad.toml").exists());
    }

    #[test]
    fn git_adapter_feature_no_git_dir_is_noop() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(&dir);
        let feat = GitAdapterFeature;
        assert_eq!(feat.name(), "git-adapter");
        feat.apply(&ctx).unwrap();
        assert!(!dir.path().join(".gitattributes").exists());
    }

    #[test]
    fn git_adapter_feature_creates_gitattributes() {
        let dir = TempDir::new().unwrap();
        std::fs::create_dir(dir.path().join(".git")).unwrap();
        let ctx = make_ctx(&dir);
        let feat = GitAdapterFeature;
        feat.apply(&ctx).unwrap();
        let content = std::fs::read_to_string(dir.path().join(".gitattributes")).unwrap();
        assert!(content.contains(".ta/project-memory/"));
        assert!(content.contains("merge=union"));
    }

    #[test]
    fn perforce_adapter_feature_is_noop() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(&dir);
        let feat = PerforceAdapterFeature;
        assert_eq!(feat.name(), "perforce-adapter");
        feat.apply(&ctx).unwrap();
    }

    #[test]
    fn pragma_context_feature_creates_planner_and_constitution() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(&dir);
        let feat = PragmaContextFeature;
        assert_eq!(feat.name(), "pragma-context");
        feat.apply(&ctx).unwrap();

        let ta_dir = dir.path().join(".ta");
        assert!(ta_dir.join("agents").join("pragma-planner.toml").exists());
        assert!(ta_dir.join("constitutions").join("kotlin.yaml").exists());

        let planner =
            std::fs::read_to_string(ta_dir.join("agents").join("pragma-planner.toml")).unwrap();
        assert!(planner.contains("pragma-planner"));
        assert!(planner.contains("2026.1.0"));
        assert!(planner.contains("matchmaking"));
        assert!(planner.contains("MatchmakingPlugin"));

        let kotlin =
            std::fs::read_to_string(ta_dir.join("constitutions").join("kotlin.yaml")).unwrap();
        assert!(kotlin.contains("ktlintCheck"));
        assert!(kotlin.contains("Suspend functions"));
        assert!(kotlin.contains("pragma-plugin-common"));
    }

    #[test]
    fn pragma_context_feature_seeds_memory() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(&dir);
        let feat = PragmaContextFeature;
        feat.apply(&ctx).unwrap();

        let memory_dir = dir.path().join(".ta").join("memory");
        assert!(memory_dir.exists());
        // Should have 3 seeded entries.
        let entries: Vec<_> = std::fs::read_dir(&memory_dir).unwrap().flatten().collect();
        assert!(
            entries.len() >= 3,
            "Expected at least 3 seeded memory entries"
        );
    }

    #[test]
    fn ue5_context_feature_seeds_memory() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(&dir);
        let feat = Ue5ContextFeature;
        assert_eq!(feat.name(), "ue5-context");
        feat.apply(&ctx).unwrap();

        let memory_dir = dir.path().join(".ta").join("memory");
        assert!(memory_dir.exists());
        let entries: Vec<_> = std::fs::read_dir(&memory_dir).unwrap().flatten().collect();
        assert!(entries.len() >= 3, "Expected at least 3 UE5 memory entries");
    }
}
