// partitioning.rs — Canonical split between shared (VCS-committed) and local
// (VCS-ignored) .ta/ files.
//
// This is the authoritative source of truth used by:
//   - `ta setup vcs` — ignore generation for Git and Perforce
//   - `ta plan shared` — display shared/local split
//   - `ta doctor` — verify local paths are properly ignored

/// Paths inside `.ta/` that should be committed to VCS and shared with the team.
/// These are configuration and agent definition files — they encode team policy.
pub const SHARED_TA_PATHS: &[&str] = &[
    "workflow.toml",
    "policy.yaml",
    "constitution.toml",
    "memory.toml",
    "bmad.toml",
    "config.toml",
    "agents/",
    "constitutions/",
    "project-memory/", // VCS-committed shared knowledge (was incorrectly "memory/")
    "personas/",
    "templates/",
    "plan_history.jsonl",   // append-only audit trail of plan phase completions
    "release-history.json", // append-only project release changelog
    "velocity-history.jsonl", // append-only committed velocity log (multi-machine)
    "goal-audit.jsonl",     // append-only goal lifecycle audit — auto-staged on apply
    "pr-template.md",
];

/// Paths inside `.ta/` that are local runtime state and must NOT be committed.
/// Committing these by accident causes clutter, credential leaks, and merge conflicts.
pub const LOCAL_TA_PATHS: &[&str] = &[
    // Config overrides (machine-local)
    "daemon.toml",
    "daemon.local.toml",
    "workflow.local.toml",
    "local.workflow.toml", // deprecated name — kept so existing files stay gitignored
    "memory.rvf",
    // Runtime directories
    "staging/",
    "store/",
    "goals/",
    "events/",
    "sessions/",
    "interactions/",
    "pr_packages/",
    "review/",
    "backups/",
    "heartbeats/",
    "workflow-runs/",
    "advisor-notes/",
    "draft-build-ctx/",
    "memory/",     // local memory cache (project-memory/ is the VCS-committed counterpart)
    "link-cache/", // cached remote project manifests (v0.16.1.5)
    // Runtime files
    "velocity-stats.jsonl",
    "audit-ledger.jsonl",
    "audit.jsonl",
    "goal-history.jsonl",
    "operations.jsonl",
    "events.jsonl",
    "change_summary.json",
    "consent.json",
    "mcp_json_original",
    "setup-progress.json",
    "taignore",
    "ide-excludes.json", // generated by ta init / ta doctor --fix; read by community editor plugins
    "human-verify-audit.jsonl", // ta_human_verify audit trail (v0.17.0.12.26)
    "human-verify-invocations.jsonl", // ta_human_verify invocation log (v0.17.0.12.26)
    "verify-audit-reviewed.jsonl", // ta_human_verify review cursor (v0.17.0.12.26)
    "verify-threshold-proposals.jsonl", // ta_human_verify threshold proposals (v0.17.0.12.26)
    // Glob patterns — gitignore prefixes these with .ta/ so they match .ta/*.log etc.
    "*.log",
    "*.pid",
    "*.lock", // replaces the specific release.lock entry
];

/// Returns only the directory entries from `LOCAL_TA_PATHS` (those ending with `/`).
///
/// Used by IDE integrations (VS Code `files.exclude`, JetBrains `DirectoryIndexExcludePolicy`)
/// to exclude TA runtime directories from file search and symbol indexing. File entries and
/// glob patterns are omitted — IDEs handle those differently.
pub fn ta_runtime_dirs() -> impl Iterator<Item = &'static str> {
    LOCAL_TA_PATHS.iter().copied().filter(|p| p.ends_with('/'))
}

/// VCS backend detected or configured for the project.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VcsBackend {
    Git,
    Perforce,
    None,
}

impl VcsBackend {
    /// Detect the VCS backend for the given project root.
    ///
    /// Check order:
    /// 1. `.git/` directory present — Git
    /// 2. `.p4config` in any parent directory or `P4PORT`/`P4CLIENT` env vars — Perforce
    /// 3. Otherwise — None
    pub fn detect(project_root: &std::path::Path) -> Self {
        // Git: .git/ directory exists, or git rev-parse succeeds.
        if project_root.join(".git").exists() {
            return Self::Git;
        }
        // Try git rev-parse (handles worktrees and submodules).
        // Clear TA agent VCS isolation env vars (set by v0.13.17.3) so we
        // detect VCS based on project_root's own repo, not the staging dir.
        let git_ok = std::process::Command::new("git")
            .args(["rev-parse", "--git-dir"])
            .current_dir(project_root)
            .env_remove("GIT_DIR")
            .env_remove("GIT_WORK_TREE")
            .env_remove("GIT_CEILING_DIRECTORIES")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);
        if git_ok {
            return Self::Git;
        }

        // Perforce: P4PORT or P4CLIENT env vars, or .p4config in ancestor dirs.
        if std::env::var("P4PORT").is_ok() || std::env::var("P4CLIENT").is_ok() {
            return Self::Perforce;
        }
        let mut dir = Some(project_root);
        while let Some(d) = dir {
            if d.join(".p4config").exists() {
                return Self::Perforce;
            }
            dir = d.parent();
        }

        Self::None
    }

    /// Machine-readable name for workflow.toml serialization.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Git => "git",
            Self::Perforce => "perforce",
            Self::None => "none",
        }
    }

    /// Check whether a `.ta/`-relative path is ignored by this project's VCS.
    ///
    /// Returns `Ok(true)` if the VCS is configured to ignore the path,
    /// `Ok(false)` if it is not (warrants a `ta setup vcs` nudge),
    /// or `Err(String)` if the VCS check itself failed.
    ///
    /// Dispatches to the per-VCS free function so callers (`ta doctor`,
    /// `ta plan shared`, `ta goal`) do not need VCS-specific branches.
    ///
    /// `VcsBackend::None` always returns `Ok(true)` — no VCS means nothing
    /// will ever be committed, so all paths are effectively "safe".
    pub fn is_path_ignored(
        &self,
        project_root: &std::path::Path,
        ta_rel_path: &str,
    ) -> Result<bool, String> {
        match self {
            Self::Git => git_is_ignored(project_root, ta_rel_path),
            Self::Perforce => p4_is_ignored(project_root, ta_rel_path),
            Self::None => Ok(true),
        }
    }
}

/// Check whether a given `.ta/` relative path is currently ignored by Git.
///
/// Returns `Ok(true)` if ignored, `Ok(false)` if tracked/untracked-but-not-ignored.
/// Returns `Err` if the check itself failed (not a git repo, git not on PATH, etc.).
pub fn git_is_ignored(project_root: &std::path::Path, ta_rel_path: &str) -> Result<bool, String> {
    let path = format!(".ta/{}", ta_rel_path);
    let output = std::process::Command::new("git")
        .args(["check-ignore", "-q", &path])
        .current_dir(project_root)
        .output()
        .map_err(|e| format!("git check-ignore failed: {}", e))?;
    // exit 0 = ignored, exit 1 = not ignored, other = error
    if output.status.success() {
        Ok(true)
    } else if output.status.code() == Some(1) {
        Ok(false)
    } else {
        Err(format!(
            "git check-ignore returned unexpected status: {:?}",
            output.status.code()
        ))
    }
}

/// Check whether a `.ta/`-relative path is excluded by Perforce's P4IGNORE rules.
///
/// Returns `Ok(true)` if the path is excluded, `Ok(false)` if it is not.
/// Returns `Err` if the command itself failed.
///
/// Requires `P4IGNORE` to be set in the environment and `p4` on `$PATH`.
/// When `P4IGNORE` is not set, Perforce has no ignore rules in effect, so
/// the path is not protected — returns `Ok(false)`.
///
/// Uses `p4 ignores -i <path>` (Helix Core 2018.2+). Output contains
/// "is excluded by" when the path is excluded.
pub fn p4_is_ignored(project_root: &std::path::Path, ta_rel_path: &str) -> Result<bool, String> {
    // Without P4IGNORE, no ignore rules are active.
    if std::env::var("P4IGNORE").is_err() {
        return Ok(false);
    }
    let path = format!(".ta/{}", ta_rel_path);
    let output = std::process::Command::new("p4")
        .args(["ignores", "-i", &path])
        .current_dir(project_root)
        .output()
        .map_err(|e| format!("p4 ignores failed: {}", e))?;
    // "p4 ignores -i <path>" prints "<path> is excluded by: ..." when ignored,
    // or "<path> is not excluded" when not.
    let stdout = String::from_utf8_lossy(&output.stdout);
    Ok(stdout.contains("is excluded by"))
}

/// The marker line used in .gitignore to identify the TA-managed block.
pub const GITIGNORE_MARKER: &str = "# Trusted Autonomy — local runtime state (do not commit)";

/// Build the `.gitignore` block for all local TA paths.
pub fn gitignore_block() -> String {
    let mut block = String::new();
    block.push_str(GITIGNORE_MARKER);
    block.push('\n');
    for path in LOCAL_TA_PATHS {
        block.push_str(&format!(".ta/{}\n", path));
    }
    block
}

/// Whether `.ta/<rest>` (the full line, e.g. `.ta/staging/`) is a recognized
/// entry — i.e. it matches something in `LOCAL_TA_PATHS` or `SHARED_TA_PATHS`,
/// including the `*.log` / `*.pid` / `*.lock` glob entries.
///
/// Used by [`update_gitignore`] / [`update_p4ignore`] to distinguish TA's own
/// generated lines (safe to regenerate) from entries a human added by hand
/// that TA doesn't know about (must be preserved, not silently dropped —
/// see v0.17.0.12.32).
fn is_recognized_ta_line(line: &str) -> bool {
    let Some(rel) = line.strip_prefix(".ta/") else {
        return false;
    };
    LOCAL_TA_PATHS
        .iter()
        .chain(SHARED_TA_PATHS.iter())
        .any(|p| {
            if let Some(suffix) = p.strip_prefix("*.") {
                rel.ends_with(suffix) && !rel.contains('/')
            } else {
                *p == rel
            }
        })
}

/// Append (or update) the TA block in the given `.gitignore` content.
///
/// Idempotent: if the marker is already present, replaces the existing block.
/// If `force` is true, always rewrites the block even if already present.
///
/// Returns `(new_content, changed, unregistered_lines)`. `unregistered_lines`
/// lists any `.ta/`-prefixed line found in the old TA block that isn't a
/// recognized `LOCAL_TA_PATHS`/`SHARED_TA_PATHS` entry — these are preserved
/// in the output (never silently dropped), but callers should surface them
/// as a warning so the entry can be registered properly (v0.17.0.12.32).
pub fn update_gitignore(existing: &str, force: bool) -> (String, bool, Vec<String>) {
    if !force && existing.contains(GITIGNORE_MARKER) {
        // Already present — nothing to do.
        return (existing.to_string(), false, Vec::new());
    }

    // Remove any existing TA block (marker line + the .ta/ lines that follow),
    // but only the lines we actually recognize — anything else that happens
    // to start with `.ta/` is preserved and reported, not dropped.
    let mut result = String::new();
    let mut in_ta_block = false;
    let mut unregistered = Vec::new();
    for line in existing.lines() {
        if line.trim() == GITIGNORE_MARKER.trim() {
            in_ta_block = true;
            continue;
        }
        if in_ta_block {
            let trimmed = line.trim();
            if trimmed.starts_with(".ta/") {
                if is_recognized_ta_line(trimmed) {
                    continue;
                }
                unregistered.push(trimmed.to_string());
                result.push_str(line);
                result.push('\n');
                continue;
            }
            in_ta_block = false;
        }
        result.push_str(line);
        result.push('\n');
    }

    // Ensure there's exactly one blank line separator before our block.
    if !result.is_empty() && !result.ends_with("\n\n") {
        if result.ends_with('\n') {
            result.push('\n');
        } else {
            result.push_str("\n\n");
        }
    }

    result.push_str(&gitignore_block());
    (result, true, unregistered)
}

/// The marker line used in .p4ignore to identify the TA-managed block.
pub const P4IGNORE_MARKER: &str = "# Trusted Autonomy — local runtime state (do not submit)";

/// Build the `.p4ignore` block for all local TA paths.
pub fn p4ignore_block() -> String {
    let mut block = String::new();
    block.push_str(P4IGNORE_MARKER);
    block.push('\n');
    for path in LOCAL_TA_PATHS {
        block.push_str(&format!(".ta/{}\n", path));
    }
    block
}

/// Append (or update) the TA block in the given `.p4ignore` content.
///
/// Idempotent: if the marker is already present, skips unless `force`.
///
/// Returns `(new_content, changed, unregistered_lines)` — see
/// [`update_gitignore`] for the meaning of `unregistered_lines`.
pub fn update_p4ignore(existing: &str, force: bool) -> (String, bool, Vec<String>) {
    if !force && existing.contains(P4IGNORE_MARKER) {
        return (existing.to_string(), false, Vec::new());
    }

    let mut result = String::new();
    let mut in_ta_block = false;
    let mut unregistered = Vec::new();
    for line in existing.lines() {
        if line.trim() == P4IGNORE_MARKER.trim() {
            in_ta_block = true;
            continue;
        }
        if in_ta_block {
            let trimmed = line.trim();
            if trimmed.starts_with(".ta/") {
                if is_recognized_ta_line(trimmed) {
                    continue;
                }
                unregistered.push(trimmed.to_string());
                result.push_str(line);
                result.push('\n');
                continue;
            }
            in_ta_block = false;
        }
        result.push_str(line);
        result.push('\n');
    }

    if !result.is_empty() && !result.ends_with("\n\n") {
        if result.ends_with('\n') {
            result.push('\n');
        } else {
            result.push_str("\n\n");
        }
    }
    result.push_str(&p4ignore_block());
    (result, true, unregistered)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gitignore_block_contains_all_local_paths() {
        let block = gitignore_block();
        assert!(block.contains(GITIGNORE_MARKER));
        for path in LOCAL_TA_PATHS {
            assert!(
                block.contains(&format!(".ta/{}", path)),
                "missing .ta/{} in gitignore block",
                path
            );
        }
    }

    #[test]
    fn update_gitignore_appends_to_empty() {
        let (result, changed, _unregistered) = update_gitignore("", false);
        assert!(changed);
        assert!(result.contains(GITIGNORE_MARKER));
        assert!(result.contains(".ta/staging/"));
    }

    #[test]
    fn update_gitignore_idempotent() {
        let (first, _, _) = update_gitignore("# existing\n", false);
        let (second, changed, _unregistered) = update_gitignore(&first, false);
        assert!(!changed, "second run should not change content");
        assert_eq!(first, second);
    }

    #[test]
    fn update_gitignore_force_rewrites() {
        let existing =
            "# existing\n# Trusted Autonomy — local runtime state (do not commit)\n.ta/staging/\n";
        let (result, changed, _unregistered) = update_gitignore(existing, true);
        assert!(changed);
        // Should contain all LOCAL_TA_PATHS, not duplicates.
        let count = result.matches(GITIGNORE_MARKER).count();
        assert_eq!(
            count, 1,
            "should only have one TA block after force rewrite"
        );
    }

    #[test]
    fn update_gitignore_preserves_existing_entries() {
        let existing = "*.log\n/dist/\n";
        let (result, changed, unregistered) = update_gitignore(existing, false);
        assert!(changed);
        assert!(result.contains("*.log"));
        assert!(result.contains("/dist/"));
        assert!(result.contains(GITIGNORE_MARKER));
        assert!(unregistered.is_empty());
    }

    /// Regression test for v0.17.0.12.32: a `.ta/`-prefixed line that was
    /// manually added to the TA block but never registered in
    /// `LOCAL_TA_PATHS` must survive a `--force` regeneration — it must NOT
    /// be silently dropped just because it happens to start with `.ta/`.
    #[test]
    fn update_gitignore_force_preserves_unregistered_entry() {
        let existing = format!(
            "{}\n.ta/staging/\n.ta/some-real-file.jsonl\n.ta/goals/\n",
            GITIGNORE_MARKER
        );
        let (result, changed, unregistered) = update_gitignore(&existing, true);
        assert!(changed);
        assert!(
            result.contains(".ta/some-real-file.jsonl"),
            "unregistered entry must survive --force, not be silently dropped:\n{}",
            result
        );
        assert_eq!(
            unregistered,
            vec![".ta/some-real-file.jsonl".to_string()],
            "the unregistered entry must be reported so the caller can warn"
        );
    }

    #[test]
    fn update_gitignore_force_still_dedupes_registered_entries() {
        let existing = format!("{}\n.ta/staging/\n.ta/staging/\n", GITIGNORE_MARKER);
        let (result, _changed, unregistered) = update_gitignore(&existing, true);
        assert!(unregistered.is_empty());
        // Registered entries are regenerated from LOCAL_TA_PATHS, so no duplicates.
        assert_eq!(result.matches(".ta/staging/").count(), 1);
    }

    #[test]
    fn p4ignore_block_contains_all_local_paths() {
        let block = p4ignore_block();
        assert!(block.contains(P4IGNORE_MARKER));
        for path in LOCAL_TA_PATHS {
            assert!(block.contains(&format!(".ta/{}", path)));
        }
    }

    #[test]
    fn update_p4ignore_idempotent() {
        let (first, _, _) = update_p4ignore("", false);
        let (second, changed, _unregistered) = update_p4ignore(&first, false);
        assert!(!changed);
        assert_eq!(first, second);
    }

    #[test]
    fn update_p4ignore_force_preserves_unregistered_entry() {
        let existing = format!(
            "{}\n.ta/staging/\n.ta/some-real-file.jsonl\n.ta/goals/\n",
            P4IGNORE_MARKER
        );
        let (result, changed, unregistered) = update_p4ignore(&existing, true);
        assert!(changed);
        assert!(
            result.contains(".ta/some-real-file.jsonl"),
            "unregistered entry must survive --force, not be silently dropped:\n{}",
            result
        );
        assert_eq!(unregistered, vec![".ta/some-real-file.jsonl".to_string()]);
    }

    /// Regression test for v0.17.0.12.32: these 4 paths were added directly to
    /// `.gitignore` (created by `ta_human_verify`'s v0.17.0.12.26 audit trail)
    /// but never registered in `LOCAL_TA_PATHS`, so a `--force` regeneration
    /// silently dropped them. Pin them explicitly so removing any one fails
    /// this test rather than surviving unnoticed until the next incident.
    #[test]
    fn local_ta_paths_includes_human_verify_audit_trail_paths() {
        for expected in [
            "human-verify-audit.jsonl",
            "human-verify-invocations.jsonl",
            "verify-audit-reviewed.jsonl",
            "verify-threshold-proposals.jsonl",
        ] {
            assert!(
                LOCAL_TA_PATHS.contains(&expected),
                "LOCAL_TA_PATHS is missing '{}' — this was the exact incident from v0.17.0.12.32",
                expected
            );
        }
    }

    #[test]
    fn vcs_detect_no_git() {
        use tempfile::TempDir;
        let dir = TempDir::new().unwrap();
        // Plain directory — no .git, no P4 env vars (env may vary in CI, so
        // only check the non-Perforce path when env is clean).
        let vcs = VcsBackend::detect(dir.path());
        // May be Perforce if P4PORT is set in the test environment; that's OK.
        assert!(
            vcs == VcsBackend::None || vcs == VcsBackend::Perforce,
            "unexpected VCS: {:?}",
            vcs
        );
    }

    #[test]
    fn vcs_detect_git_dot_git_dir() {
        use tempfile::TempDir;
        let dir = TempDir::new().unwrap();
        std::fs::create_dir(dir.path().join(".git")).unwrap();
        assert_eq!(VcsBackend::detect(dir.path()), VcsBackend::Git);
    }

    #[test]
    fn shared_paths_not_in_local() {
        for shared in SHARED_TA_PATHS {
            assert!(
                !LOCAL_TA_PATHS.contains(shared),
                "{} appears in both SHARED and LOCAL lists",
                shared
            );
        }
    }

    #[test]
    fn project_memory_in_shared_not_memory() {
        assert!(
            SHARED_TA_PATHS.contains(&"project-memory/"),
            "SHARED_TA_PATHS must contain 'project-memory/' (the VCS-committed knowledge dir)"
        );
        assert!(
            !SHARED_TA_PATHS.contains(&"memory/"),
            "SHARED_TA_PATHS must not contain 'memory/' — that is the local cache dir"
        );
    }

    #[test]
    fn goal_audit_in_shared_paths() {
        assert!(
            SHARED_TA_PATHS.contains(&"goal-audit.jsonl"),
            "goal-audit.jsonl must be in SHARED_TA_PATHS (auto-staged on apply)"
        );
    }

    #[test]
    fn local_paths_include_all_required_dirs_and_globs() {
        for required in &[
            "pr_packages/",
            "review/",
            "backups/",
            "heartbeats/",
            "workflow-runs/",
            "advisor-notes/",
            "draft-build-ctx/",
            "memory/",
            "*.log",
            "*.pid",
            "*.lock",
        ] {
            assert!(
                LOCAL_TA_PATHS.contains(required),
                "LOCAL_TA_PATHS missing required entry: {}",
                required
            );
        }
        // release.lock must not exist as a specific entry — replaced by *.lock glob.
        assert!(
            !LOCAL_TA_PATHS.contains(&"release.lock"),
            "release.lock must not be a specific entry — use *.lock glob instead"
        );
    }

    #[test]
    fn link_cache_in_local_ta_paths() {
        assert!(
            LOCAL_TA_PATHS.contains(&"link-cache/"),
            "link-cache/ must be in LOCAL_TA_PATHS so remote manifests are not committed"
        );
    }

    #[test]
    fn ta_runtime_dirs_are_complete() {
        let dirs: Vec<&str> = super::ta_runtime_dirs().collect();
        // Must include all known runtime directories.
        for required in &[
            "staging/",
            "store/",
            "goals/",
            "sessions/",
            "interactions/",
            "pr_packages/",
            "review/",
            "backups/",
            "heartbeats/",
            "workflow-runs/",
            "advisor-notes/",
            "draft-build-ctx/",
            "memory/",
            "link-cache/",
        ] {
            assert!(
                dirs.contains(required),
                "ta_runtime_dirs() missing required directory entry: {}",
                required
            );
        }
        // Must not include non-directory entries.
        for dir in &dirs {
            assert!(
                dir.ends_with('/'),
                "ta_runtime_dirs() returned non-directory entry: {}",
                dir
            );
        }
        // The gitignore block must contain every directory returned by ta_runtime_dirs().
        let block = gitignore_block();
        for dir in &dirs {
            assert!(
                block.contains(&format!(".ta/{}", dir)),
                "gitignore block is missing ta_runtime_dirs() entry: .ta/{}",
                dir
            );
        }
    }

    // ── v0.17.0.12.32 item 2: static check for unregistered `.ta/` paths ──

    /// Recursively collect every `.rs` file under `apps/` and `crates/`,
    /// skipping `target/` build output.
    fn collect_rs_files(root: &std::path::Path, out: &mut Vec<std::path::PathBuf>) {
        let Ok(entries) = std::fs::read_dir(root) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
                if name == "target" || name.starts_with('.') {
                    continue;
                }
                collect_rs_files(&path, out);
            } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
                out.push(path);
            }
        }
    }

    /// Extract the literal argument of every `.join("<literal>")` call that
    /// directly follows a `.join(".ta")` call in `content` — i.e. `X.join(".ta").join("foo")`
    /// yields `"foo"`. This is a deliberately narrow heuristic (source text
    /// scanning, not real parsing): it only catches the direct-chain form,
    /// not `let ta_dir = x.join(".ta"); ta_dir.join("foo")`. It's a safety
    /// net on top of code review, not a substitute for it.
    fn extract_dot_ta_join_literals(content: &str) -> Vec<String> {
        const MARKER: &str = ".join(\".ta\")";
        let mut results = Vec::new();
        let mut search_from = 0;
        while let Some(pos) = content[search_from..].find(MARKER) {
            let abs = search_from + pos + MARKER.len();
            let rest = content[abs..].trim_start();
            if let Some(after_join) = rest.strip_prefix(".join(\"") {
                if let Some(end) = after_join.find('"') {
                    results.push(after_join[..end].to_string());
                }
            }
            search_from = abs;
        }
        results
    }

    /// Pre-existing `.ta/`-relative paths, discovered by this test's own
    /// heuristic scan, that are written directly under `.ta/` somewhere in
    /// the codebase but have not yet been triaged into `LOCAL_TA_PATHS` or
    /// `SHARED_TA_PATHS`. This backlog predates this test (v0.17.0.12.32
    /// added the mechanism; it did not audit 249 prior phases of `.ta/`
    /// writes). Do NOT add new entries here to silence a failure — that
    /// defeats the point. Register genuinely new `.ta/` writes in
    /// `LOCAL_TA_PATHS`/`SHARED_TA_PATHS` instead. This list should only
    /// ever shrink, as each path gets triaged in a follow-up phase.
    const KNOWN_UNTRIAGED_GAPS: &[&str] = &[
        "action-log.jsonl",
        "advisor",
        "advisor-history.json",
        "advisor-history.jsonl",
        "advisor-intent",
        "advisor-patches",
        "advisor-pending-actions.jsonl",
        "agent-recommendations.jsonl",
        "apply-base.json",
        "apply.journal",
        "audit.key",
        "autonomous-loop-state.json",
        "baselines",
        "cache",
        "community-cache",
        "community-resources.toml",
        "community_feedback.json",
        "compression",
        "config.yaml",
        "connectors",
        "constitution.md",
        "conversations",
        "daemon-tokens.json",
        "docs",
        "drafts",
        "email-manager-status.json",
        "email-review-queue.jsonl",
        "event-routing.yaml",
        "foo", // test fixture literal (not a real runtime path)
        "frameworks.toml",
        "governed",
        "hooks.toml",
        "human-verify",
        "intake-queue.jsonl",
        "keys",
        "knowledge",
        "links.toml",
        "logs",
        "mcp-agent.json",
        "mcp-servers",
        "memory_out.json",
        "memory_snapshot.md",
        "messaging-audit.jsonl",
        "milestones",
        "office-override.yaml",
        "plan_base.md",
        "plugins",
        "pr-packages",
        "project-manifest.md",
        "project.toml",
        "release-config.yaml",
        "release.yaml",
        "review_queue",
        "routing-decisions.jsonl",
        "sha-fs",
        "shell.toml",
        "social-audit.jsonl",
        "solutions",
        "summary-exempt",
        "ta-progress.json",
        "team.toml",
        "tmp",
        "tokens",
        "triggers",
        "verify-failures.jsonl",
        "work-plan.json",
        "work-plans",
        "workflow-state",
        "workflow-templates",
        "workflows",
    ];

    fn is_known_or_allowlisted(bare: &str) -> bool {
        let known = LOCAL_TA_PATHS
            .iter()
            .chain(SHARED_TA_PATHS.iter())
            .any(|p| {
                let p_bare = p.trim_end_matches('/');
                if let Some(suffix) = p.strip_prefix("*.") {
                    bare.ends_with(suffix) && !bare.contains('/')
                } else {
                    p_bare == bare
                }
            });
        known || KNOWN_UNTRIAGED_GAPS.contains(&bare)
    }

    /// Safety net for v0.17.0.12.32: fail CI if a *new* `.ta/`-relative
    /// literal path shows up in the source that isn't registered in
    /// `LOCAL_TA_PATHS`/`SHARED_TA_PATHS` (or the known pre-existing
    /// backlog above). This is what should have caught the missing
    /// `human-verify-audit.jsonl` et al. before they ever reached
    /// `.gitignore` by hand.
    #[test]
    fn all_direct_dot_ta_join_literals_are_registered_or_allowlisted() {
        let manifest_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let workspace_root = manifest_dir
            .parent()
            .and_then(|p| p.parent())
            .expect("crates/ta-workspace should be two levels below the workspace root");

        let mut files = Vec::new();
        for top in ["apps", "crates"] {
            let dir = workspace_root.join(top);
            if dir.exists() {
                collect_rs_files(&dir, &mut files);
            }
        }
        assert!(
            !files.is_empty(),
            "expected to find .rs source files under {}/{{apps,crates}} — \
             workspace root detection is broken",
            workspace_root.display()
        );

        let mut found = std::collections::BTreeSet::new();
        for file in &files {
            let content = std::fs::read_to_string(file).unwrap_or_default();
            for lit in extract_dot_ta_join_literals(&content) {
                found.insert(lit);
            }
        }

        let unaccounted: Vec<&String> = found
            .iter()
            .filter(|p| !is_known_or_allowlisted(p.trim_end_matches('/')))
            .collect();

        assert!(
            unaccounted.is_empty(),
            "Found .ta/ literal path(s) written by TA code that are not registered in \
             LOCAL_TA_PATHS or SHARED_TA_PATHS (crates/ta-workspace/src/partitioning.rs), \
             and not in this test's KNOWN_UNTRIAGED_GAPS allowlist: {:?}\n\
             Register each new path in LOCAL_TA_PATHS (if it's local runtime state) or \
             SHARED_TA_PATHS (if it should be committed).",
            unaccounted
        );
    }
}
